### ISSUE TITLE
Pluto query is buggy 

### ISSUE THREAD

**Issue by umgbhalla** [space-voyager-21/space-voyager#10]
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjViODljOTItOWNhYS00NjNiLWFjNjItNDNiZWRhOWU4NWFhIiwiZGVwbG95X2lkIjoiNjE1NmEwNmE5OWQ5YWUwMDA3ZjExYTVmIiwiaWQiOiIwZGM4NDRmOS1hOTZjLTQzMmItYTE3OC01ZThiY2NmZGU0ZmIifQ==)

### Description of issue
When Searching for Drawf planet pluto , site crashes

### Expected result
No moons found or Wronge planet

### Actual result
Crashed site , [gif attached]

### Steps to reproduce
1. Search Pluto and press enter
2. check console for logs

```
Path:      /?utm_source=github&utm_campaign=bot_dp
Browser:   Firefox 92.0 on Linux x86_64
Viewport:  1850 x 959 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-9--space-voyager.netlify.app%2F%3Futm_source%3Dgithub%26utm_campaign%3Dbot_dp&os=OS%20X&os_version=Big%20Sur&browser=Firefox&browser_version=92.0&resolution=1850x959&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #9](https://deploy-preview-9--space-voyager.netlify.app/?utm_source=github&utm_campaign=bot_dp)

**Comment by rosdyana** [comment]
The problem here was missing planet image, I think if the asset is not available, it should use the placeholder.

```
const tryRequire = (path) => {
    try {
     return require(`${path}`);
    } catch (err) {
     return null;
    }
  };
```
````
<div className="planimg">
            <img src={tryRequire("../assets/" + data.englishName + ".png") 
            ? tryRequire("../assets/" + data.englishName + ".png").default 
            : img1} alt="planet" />
          </div>
````

These snippet should fix the crash

**Comment by chaitanyks** [comment]
Issue fixed.

**Comment by mohittk** [comment]
> Issue fixed.

Yes! Thankyou. Looking forward for more contributions. @chaitanyks
