### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by Tishasoumya-02** [space-voyager-21/space-voyager#17]
A loader when the API is busy fetching the data would look great.

**Comment by Tishasoumya-02** [comment]
Want to work on it.

**Comment by mohittk** [comment]
That's cool! I had one additional request
Fix the font in your last pr, make it similar to theme of website.
And put the satellite svg in smooth motion on its place, like done by srijit's PR.

**Comment by Tishasoumya-02** [comment]
Sure!
