### ISSUE TITLE
Needed ISS live location with Google map

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#18]
Basically I needed someone to make a separate page for _SPACE VOYAGER_ website, which will show live location of ISS (international space station) API, through google maps. I need this to be done without any google map error.

**Comment by meerhamzadev** [comment]
hey @mohittk, I would like to implement this. Can you provide me the API?

**Comment by mohittk** [comment]
> hey @mohittk, I would like to implement this. Can you provide me the API?

Sounds Good! 
Yea! I'm attaching the link.
http://api.open-notify.org/iss-now.json

**Comment by mohittk** [comment]
Issue closed! task accomplished by @MeerHamza1421
