### ISSUE TITLE
Needed more ideas regarding different tabs to be added 

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#2]
Linking to previous issue, of idea regarding adding NASA's APIs for landing page. That's really appreciable. Similar to that I needed more clarity what else we can add, such as ISS position tracker, etc.

**Comment by Tishasoumya-02** [comment]
There are many NASA APIs that can be used. I myself used them in building one of my projects like SSD/CNEOS(Solar System Dynamics and center for near-earth-object studies).  You can have different pages dedicated to being these APIs.

**Comment by mohittk** [comment]
> There are many NASA APIs that can be used. I myself used them in building one of my projects like SSD/CNEOS(Solar System Dynamics and center for near-earth-object studies). You can have different pages dedicated to being these APIs.

Yes! through this issue, my point was mainly to find out different pages, that we can add, which will together make a huge SPACE WEBSITE.
