### ISSUE TITLE
Needed to add "Astronomy pic of the day" page seperately on website.

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#20]
The all I want is to use the NASA open API and create a seperate page on Space-voyager website, like a button so that on click astronomy page opens.

**Comment by Chitvan14** [comment]
Can i work on this?

**Comment by mohittk** [comment]
Okay! You can. But make sure that you create a separate page for it, routed to main landing page (in short, create a button on landing page), accordance with the theme of website. @Chitvan14

**Comment by Chitvan14** [comment]
Sure, Can you provide the api @mohittk?

**Comment by mohittk** [comment]
> Sure, Can you provide the api @mohittk?

Yes sure!
Here it is https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY
For documentation info. Refer https://api.nasa.gov/

And Join discord server for this repo : Link in description

**Comment by mohittk** [comment]
> Sure, Can you provide the api @mohittk?

@Chitvan14 Are you working upon this issue. Please confirm.

**Comment by metavinayak** [comment]
@mohittk I can work on this feature. I have used the API before. It will be nice if you can give an idea what should the webpage look like,apart from the theme .I'll add the button too.

**Comment by abh80** [comment]
Can i work on this?

**Comment by mohittk** [comment]
> Can i work on this?

Yea! sure you can.
