### ISSUE TITLE
(JS-0125) Found the usage of undeclared variables

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#22]
## Description
Variable that are not defined but they are being used in the code. This would give a potential errors that may break the code. It might have happen due to mistype of the variable name.

## Occurrences
There are 7 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/space-voyager-21/space-voyager/issue/JS-0125/occurrences/](https://deepsource.io/gh/space-voyager-21/space-voyager/issue/JS-0125/occurrences/)

**Comment by alammoiz** [comment]
Please assign to me @mohittk

**Comment by mohittk** [comment]
> Please assign to me @mohittk

Ohh yea! For sure. Have you checked that occurences?

**Comment by ramdevcm** [comment]
Please assign to me

**Comment by ramdevcm** [comment]
I got all 5 test passed
