### ISSUE TITLE
ISS marker to be moved at interval of 3 sec, Satellitepng image in place of marker.

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#27]
I needed marker to be moved at interval of 3 sec, and in addition to it, change the marker from red one to satellitepng

**Comment by meerhamzadev** [comment]
Hey can I work on this too?

**Comment by mohittk** [comment]
> Hey can I work on this too?

Yea! Go for it.

**Comment by meerhamzadev** [comment]
Hey @mohittk, I implement this requirement, but I'm facing that behavior. It refreshes the whole page after 3 sec when it fetched data from API. 
 
![screen-recording(1)](https://user-images.githubusercontent.com/60890818/135766329-3a79d551-3678-4672-8d49-c5b7691f34e5.gif)

**Comment by mohittk** [comment]
> Hey @mohittk, I implement this requirement, but I'm facing that behavior. It refreshes the whole page after 3 sec when it fetched data from API.
> 
> ![screen-recording(1)](https://user-images.githubusercontent.com/60890818/135766329-3a79d551-3678-4672-8d49-c5b7691f34e5.gif)

Whole page you mean the Google content page or the whole web page?  and also why this is appearing ?  
_page can't load correctly_

**Comment by meerhamzadev** [comment]
It's because I think you haven't configured billing account yet.

**Comment by mohittk** [comment]
> It's because I think you haven't configured billing account yet.

Okay! I need to do that. I think for solving this page refreshing issue, useffect is not the solution.

**Comment by iamvaiibhav19** [comment]
@MeerHamza1421 Hello! is this issue fixed? can i help you with anything?

**Comment by meerhamzadev** [comment]
@iamvaiibhav19 no it's not fixed yet, I'm busy and won't be able to work on it now. Would you like to give it a try?

**Comment by iamvaiibhav19** [comment]
> @iamvaiibhav19 no it's not fixed yet, I'm busy and won't be able to work on it now. Would you like to give it a try?
> 

Yes Why not! Assign it to me I will try to fix it.

**Comment by umgbhalla** [comment]
assigned

**Comment by iamvaiibhav19** [comment]
> assigned

Hey can you just ellaborate what's an issue?

**Comment by meerhamzadev** [comment]
@iamvaiibhav19 Current behaviour is when user click view iss location, the current coordinates of the satellite fetched via API and passed to maps Api and the location of the satellite displayed via marker in the map. We want to update the marker after every 3 sec means after every 3 sec the Cordinates are refetched by Api and marker updates according to the coordinates. The issue we face as mentioned above the WHOLE map section also reloading with marker by using the setInterval fumction.

**Comment by mohittk** [comment]
> > assigned
> 
> Hey can you just ellaborate what's an issue?

The google map marker position is to be refreshed at interval of every 3 sec.
But the problem was the whole google map content was refrshing.
Can you fix it?

**Comment by iamvaiibhav19** [comment]
> @iamvaiibhav19 Current behaviour is when user click view iss location, the current coordinates of the satellite fetched via API and passed to maps Api and the location of the satellite displayed via marker in the map. We want to update the marker after every 3 sec means after every 3 sec the Cordinates are refetched by Api and marker updates according to the coordinates. The issue we face as mentioned above the WHOLE map section also reloading with marker by using the setInterval fumction.

Ohh! got the issue. I will try to fix it.

**Comment by mohittk** [comment]
> > @iamvaiibhav19 Current behaviour is when user click view iss location, the current coordinates of the satellite fetched via API and passed to maps Api and the location of the satellite displayed via marker in the map. We want to update the marker after every 3 sec means after every 3 sec the Cordinates are refetched by Api and marker updates according to the coordinates. The issue we face as mentioned above the WHOLE map section also reloading with marker by using the setInterval fumction.
> 
> Ohh! got the issue. I will try to fix it.

Yes! You got it correct. Just try to refresh the marker.

**Comment by iamvaiibhav19** [comment]
> > > @iamvaiibhav19 Current behaviour is when user click view iss location, the current coordinates of the satellite fetched via API and passed to maps Api and the location of the satellite displayed via marker in the map. We want to update the marker after every 3 sec means after every 3 sec the Cordinates are refetched by Api and marker updates according to the coordinates. The issue we face as mentioned above the WHOLE map section also reloading with marker by using the setInterval fumction.
> > 
> > Ohh! got the issue. I will try to fix it.
> 
> Yes! You got it correct. Just try to refresh the marker.
> 

Yes Sure!

**Comment by mohittk** [comment]
> > > > @iamvaiibhav19 Current behaviour is when user click view iss location, the current coordinates of the satellite fetched via API and passed to maps Api and the location of the satellite displayed via marker in the map. We want to update the marker after every 3 sec means after every 3 sec the Cordinates are refetched by Api and marker updates according to the coordinates. The issue we face as mentioned above the WHOLE map section also reloading with marker by using the setInterval fumction.
> > > 
> > > 
> > > Ohh! got the issue. I will try to fix it.
> > 
> > 
> > Yes! You got it correct. Just try to refresh the marker.
> 
> Yes Sure!

Any update? @iamvaiibhav19

**Comment by iamvaiibhav19** [comment]
> > > > > @iamvaiibhav19 Current behaviour is when user click view iss location, the current coordinates of the satellite fetched via API and passed to maps Api and the location of the satellite displayed via marker in the map. We want to update the marker after every 3 sec means after every 3 sec the Cordinates are refetched by Api and marker updates according to the coordinates. The issue we face as mentioned above the WHOLE map section also reloading with marker by using the setInterval fumction.
> > > > 
> > > > 
> > > > Ohh! got the issue. I will try to fix it.
> > > 
> > > 
> > > Yes! You got it correct. Just try to refresh the marker.
> > 
> > Yes Sure!
> 
> Any update? @iamvaiibhav19 

I tried Doing every changes but the map is rendering after 3 sec! So I think this Library which you have used for Map won't allow to move the marker! Else what we can do is! We can change the library for maps and using live location api for satellite we can fetch the longitude and latitude respectively! And Then we will be able to move the marker! Is it okay if I try any other libraries?

**Comment by mohittk** [comment]
Umm.. okay. Go for it. Make sure we don't get any error. The page should be cleaned with moving marker

**Comment by mohittk** [comment]
> > > > > > @iamvaiibhav19 Current behaviour is when user click view iss location, the current coordinates of the satellite fetched via API and passed to maps Api and the location of the satellite displayed via marker in the map. We want to update the marker after every 3 sec means after every 3 sec the Cordinates are refetched by Api and marker updates according to the coordinates. The issue we face as mentioned above the WHOLE map section also reloading with marker by using the setInterval fumction.
> > > > > 
> > > > > 
> > > > > Ohh! got the issue. I will try to fix it.
> > > > 
> > > > 
> > > > Yes! You got it correct. Just try to refresh the marker.
> > > 
> > > 
> > > Yes Sure!
> > 
> > 
> > Any update? @iamvaiibhav19
> 
> I tried Doing every changes but the map is rendering after 3 sec! So I think this Library which you have used for Map won't allow to move the marker! Else what we can do is! We can change the library for maps and using live location api for satellite we can fetch the longitude and latitude respectively! And Then we will be able to move the marker! Is it okay if I try any other libraries?

Umm.. okay. Go for it. Make sure we don't get any error. The page should be cleaned with moving marker

**Comment by iamvaiibhav19** [comment]
> marker

Okayy! Let me try
