### ISSUE TITLE
updates at the frontend

### ISSUE THREAD

**Issue by daedraMex** [space-voyager-21/space-voyager#3]
Right now the search bar is aligned to the right. What do you think about some improvements in the frontend (search bar, update a icon, update how planet info is displayed for beatter reading? I could share with you a design, if it is ok , I could made the updates
![Captura de pantalla 2021-09-29 081920](https://user-images.githubusercontent.com/25911909/135277472-f8d9ad22-a063-4b55-b275-f151d3e9ee88.png)
s.
![Captura de pantalla 2021-09-29 082653](https://user-images.githubusercontent.com/25911909/135277611-3ba7e8a4-85b3-4d4c-a383-34f3d32198da.png)

**Comment by mohittk** [comment]
> Right now the search bar is aligned to the right. What do you think about some improvements in the frontend (search bar, update a icon, update how planet info is displayed for beatter reading? I could share with you a design, if it is ok , I could made the updates.

That will be really cool! I am eager to see the way you want to display the information. Please do share design (FIGMA) file. 
Please join the discord server for further communication, link mentioned in "ABOUT" at repo page.

**Comment by mohittk** [comment]
@Any28Flo Are you right there? Working upon it?
If not, confirm it to me.
