### ISSUE TITLE
CSS needed to be updated with proper flex. on landing page

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#30]
![image](https://user-images.githubusercontent.com/79041510/135845188-d32b1589-898c-43a1-945b-a09c501adf03.png)

@gaurav147-star Have a look, I'll assign it to you.

**Comment by gaurav147-star** [comment]
@mohittk ya,sure

**Comment by mohittk** [comment]
> @mohittk ya,sure

I needed that blocks to be fixed with equal distance between them, and of same size
