### ISSUE TITLE
Needed autosuggestion in search-bar for satellite page.

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#34]
While entering query in search bar, there should be pane displaying autosuggestion for names of satellites.

**Comment by alammoiz** [comment]
Is it working for other categories?

**Comment by mohittk** [comment]
> Is it working for other categories?

No, not yet!

**Comment by PaulKovalov** [comment]
Hi! Can you assign this issue to me please

**Comment by mohittk** [comment]
> Hi! Can you assign this issue to me please

Okay! No problem.
