### ISSUE TITLE
Needed CSS loader on ISS page, instead of loading text

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#35]
I need loading text to be replaced by a loader purely from CSS, at center of page .
Checkout here.
Add this one.
![image](https://user-images.githubusercontent.com/79041510/135997808-3f650ca6-3e6a-4ead-8b69-a7bcfaf75979.png)

https://loading.io/css/

**Comment by alammoiz** [comment]
I would love to do this task, Please assign it to me @mohittk

**Comment by mohittk** [comment]
> I would love to do this task, Please assign it to me @mohittk

Ohh sure!

**Comment by alammoiz** [comment]
Created PR https://github.com/space-voyager-21/space-voyager/pull/38 @mohittk 
Please review it
