### ISSUE TITLE
Need Axios API usage, and Error page

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#4]
I want someone to create an error page while searching for the planet name which is incorrect. And instead of present API structure, I need AXIOS to be added.

**Comment by srijit2002** [comment]
can you please assign it to me?

**Comment by mohittk** [comment]
> can you please assign it to me?

Sure! will do. I had a request, before coding Error page, please share the design file with me on discord server or here only.

**Comment by srijit2002** [comment]
@mohittk ok
