### ISSUE TITLE
Satellite page styling issues in smaller size device

### ISSUE THREAD

**Issue by minhhang107** [space-voyager-21/space-voyager#44]
**Describe the bug**
Satellite page has some styling issues when viewed on phone/tablet screens:

1. Satellite image is covering other components (covering `Submit` button on phone screen, covering `Search bar` on tablet screen) (see screenshot 1)
2. When there's no result for search, error texts are not centered (see screenshot 2)
3. When there's no result for search, error text shows "We don't know about the **planet**.." (see screenshot 2)

**To Reproduce**
1. Go to https://space-voyager.vercel.app/satellite on a mobile device
2. Search for an invalid satellite (eg: abc)
3. See error

**Expected behavior**
1. Satellite image should not cover any other components
2. When there's no result for search, error texts should be centered
3. When there's no result for search, error text should show "We don't know about the **satellite**.."

**Screenshots**

![voyager2](https://user-images.githubusercontent.com/55411709/136237529-b8470b2b-54df-4fbf-b2fe-97f9f2895ae8.jpg)

![voyager1](https://user-images.githubusercontent.com/55411709/136237549-58ea45fc-0565-4373-add5-611856e5765e.jpg)

**Comment by minhhang107** [comment]
I would like to work on this issue. Can I be assigned?

**Comment by mohittk** [comment]
> **Describe the bug** Satellite page has some styling issues when viewed on phone/tablet screens:
> 
> 1. Satellite image is covering other components (covering `Submit` button on phone screen, covering `Search bar` on tablet screen) (see screenshot 1)
> 2. When there's no result for search, error texts are not centered (see screenshot 2)
> 3. When there's no result for search, error text shows "We don't know about the **planet**.." (see screenshot 2)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to [space-voyager.vercel.app/satellite](https://space-voyager.vercel.app/satellite) on a mobile device
> 2. Search for an invalid satellite (eg: abc)
> 3. See error
> 
> **Expected behavior**
> 
> 1. Satellite image should not cover any other components
> 2. When there's no result for search, error texts should be centered
> 3. When there's no result for search, error text should show "We don't know about the **satellite**.."
> 
> **Screenshots**
> 
> ![voyager2](https://user-images.githubusercontent.com/55411709/136237529-b8470b2b-54df-4fbf-b2fe-97f9f2895ae8.jpg)
> 
> ![voyager1](https://user-images.githubusercontent.com/55411709/136237549-58ea45fc-0565-4373-add5-611856e5765e.jpg)

Ohh Yea! I observed the issues very well. Glad that you saw that so closely. Can you fix them? @minhhang107

**Comment by mohittk** [comment]
> I would like to work on this issue. Can I be assigned?

Yea! sure.
All the best.
