### ISSUE TITLE
show planet info on scroll instead of search 

### ISSUE THREAD

**Issue by 44Chann** [space-voyager-21/space-voyager#48]
as we  can see if we want to get a info about any planet then we need to search for it what if you scroll down and get info 
also that search can be moved on to the landing page you can search for satellites and other things right away

**Comment by omkar342** [comment]
Instead of that we add a select instead of search to show info about all the planets that we can show. And this will also improve the UX of the website. Let me know your thoughts @yes-vikash.

**Comment by mohittk** [comment]
@yes-vikash We should go with the idea of @omkar342 , as it is already applied in satellites page of "space-voyager" website. Work on that, make a search autosuggestions in planets too. For reference, see the satellites page
https://space-voyager.vercel.app/satellite

**Comment by 44Chann** [comment]
@omkar342 that's good

**Comment by mohittk** [comment]
I have assigned you @yes-vikash

**Comment by omkar342** [comment]
Hey, @mohittk actually I was not saying about autosuggestions in search instead I was saying that if we use select HTML tag instead of search then our user can select between the available planets, and by choosing any one of the planets they can get the info about that planet. In this way, our user will get info regarding planets without manually typing the name of that particular planet.

**Comment by mohittk** [comment]
> Hey, @mohittk actually I was not saying about autosuggestions in search instead I was saying that if we use select HTML tag instead of search then our user can select between the available planets, and by choosing any one of the planets they can get the info about that planet. In this way, our user will get info regarding planets without manually typing the name of that particular planet.

Still it's not clear to me. Join discord server https://discord.gg/FpEK9AqbCf
Discuss there.

**Comment by mohittk** [comment]
@omkar342 You mean to say, we'll keep planet buttons on the page, where user will click and explore.
I got ur point. But bro here we are using api, which has lots of planets info apart from 9 planets.
Anyways, we can just make that type of thing for 9 planets.

**Comment by omkar342** [comment]
Yes @mohittk, actually I didn't consider the factor API while thinking about my idea. But to let people know more information about more planets apart from the planets in our solar system I think we should mention the name of few planets which are unknown to most of the people because the average person who is gonna visit this website don't know the name of the single planet which is out of our solar system.

**Comment by mohittk** [comment]
> Yes @mohittk, actually I didn't consider the factor API while thinking about my idea. But to let people know more information about more planets apart from the planets in our solar system I think we should mention the name of few planets which are unknown to most of the people because the average person who is gonna visit this website don't know the name of the single planet which is out of our solar system.

That's something really interesting. I think you should start working on it? should I assign you?

**Comment by omkar342** [comment]
Yes, but I think first of all I should create a new issue for this. What do you think?

**Comment by 44Chann** [comment]
> > Yes @mohittk, actually I didn't consider the factor API while thinking about my idea. But to let people know more information about more planets apart from the planets in our solar system I think we should mention the name of few planets which are unknown to most of the people because the average person who is gonna visit this website don't know the name of the single planet which is out of our solar system.
> 
> That's something really interesting. I think you should start working on it? should I assign you?

definitely a cool idea to let people know more about exoplanets and all

**Comment by 44Chann** [comment]
> Yes, but I think first of all I should create a new issue for this. What do you think?
definitely
