### ISSUE TITLE
Add the names of some popular planets on planets page.

### ISSUE THREAD

**Issue by omkar342** [space-voyager-21/space-voyager#49]
Hey @mohittk, as we discussed earlier I think we should add the name of a few popular planets which are not located in our solar system to the planet page to let people know more about different planets. I have an idea of adding those names as a button above the input on the planets page. And by clicking on that button we can get its information. Let me know if you have any suggestions for me. And please assign this to me.

**Comment by mohittk** [comment]
@omkar342 
hey! bro
@chaitanyks has already made the pull request for this issue, after creating his own issue.
So I'm not closing this issue rn
If you have any idea further, please do inform.

**Comment by omkar342** [comment]
Yes actually I saw that & it's really great. But all those planets are known to everyone. And I am thinking of adding names of unknown planets & we can still add those names above input. Let me know what do you think about this.
