### ISSUE TITLE
Front end is not showing any information 

### ISSUE THREAD

**Issue by roshaan005** [space-voyager-21/space-voyager#5]
I have tried using the app and the front end for some reason is broken ,  I can work on this issue 

## suggestion
I would highly suggest adding an *enter* button as it is a good approach from a UX point of view.
I would love to work on this issue 

## screenshot of the bug 
![Uploading Screenshot from 2021-09-29 22-02-22.png…]()

**Comment by mohittk** [comment]
> I have tried using the app and the front end for some reason is broken , I can work on this issue
> 
> suggestion
> I would highly suggest adding an enter button as it is a good approach from a UX point of view.
> I would love to work on this issue
> 
> screenshot of the bug

See, I have already assigned task of error page to SRIJAN, so he'll be working on it. Now, coming to enter button suggestion, you are right, as we can put both of them, like onKeyPress and enter button. So, you can work on that part. And add labels to your issue

**Comment by roshaan005** [comment]
thank you so much! I ll work on the enter button.

**Comment by mohittk** [comment]
@roshaan005 have your joined discord server? link in about section of REPO

**Comment by roshaan005** [comment]
I will join

**Comment by chaitanyks** [comment]
Issue fixed.
