### ISSUE TITLE
I have added planet rotating icons on the /planet page below search bar.

### ISSUE THREAD

**Issue by chaitanyks** [space-voyager-21/space-voyager#50]
I have added rotating planet icons on the /planet page below the search bar. I have completed the code changes if you are interested then I will raise the pr for that.

![image](https://user-images.githubusercontent.com/25911060/136655892-419c3781-e8f2-47fa-bbca-57f007781ebe.png)

Remark: Planets are clickable. And they follow the same submit behavior.

**Comment by mohittk** [comment]
> I have added rotating planet icons on the /planet page below the search bar. I have completed the code changes if you are interested then I will raise the pr for that.
> 
> ![image](https://user-images.githubusercontent.com/25911060/136655892-419c3781-e8f2-47fa-bbca-57f007781ebe.png)
> 
> Remark: Planets are clickable. And they follow the same submit behavior.

Looks really nice!
