### ISSUE TITLE
Add hover effect to those 9 planets.

### ISSUE THREAD

**Issue by omkar342** [space-voyager-21/space-voyager#57]
Hey @mohittk, I think we should add a hover effect to all the images of those 9 planets on the planets page. As it's looking very plane on hovering on it right now. Where we can increase or decrease the scale of that images. Let me know your thoughts on this.

**Comment by mohittk** [comment]
> Hey @mohittk, I think we should add a hover effect to all the images of those 9 planets on the planets page. As it's looking very plane on hovering on it right now. Where we can increase or decrease the scale of that images. Let me know your thoughts on this.

You can do it, but it is very small change, so think of any other change too, so that I can accept the PR.

**Comment by omkar342** [comment]
Yes, I will think of some ideas while working on it.

**Comment by omkar342** [comment]
Hey @mohittk, do you know how we can add both animation and hover effect to any element? Because I am not able to do that. As either animation of rotation is working or the hover effect is working on the image. I am not able to do both. Do you have any suggestions?

**Comment by mohittk** [comment]
> Hey @mohittk, do you know how we can add both animation and hover effect to any element? Because I am not able to do that. As either animation of rotation is working or the hover effect is working on the image. I am not able to do both. Do you have any suggestions?

I don't have any idea regarding that one. Research for it on google.

**Comment by tyler-morales** [comment]
I can help with this! Let me know if you want to assign it to me :)

**Comment by mohittk** [comment]
> I can help with this! Let me know if you want to assign it to me :)

Elaborate, what changes you gonna make to make the user-interface better?
Particularly in this one.

**Comment by tyler-morales** [comment]
@mohittk Currently, I don't see any focus, hover, or selected styles on any of the planets. 

1. I'd like to add hover and focus style to increase the scale of the planet
2. Add a selected style: a ring around each planet when it is selected

**Comment by mohittk** [comment]
> @mohittk Currently, I don't see any focus, hover, or selected styles on any of the planets.
> 
> 1. I'd like to add hover and focus style to increase the scale of the planet
> 2. Add a selected style: a ring around each planet when it is selected

umm.. okay! Go for it. add something new design or feature in addition to hover effects.

**Comment by mohittk** [comment]
Solved in #66 !
