### ISSUE TITLE
Card image on landing page don't have rounded borders

### ISSUE THREAD

**Issue by abh80** [space-voyager-21/space-voyager#58]
It appears that the card image on the landing page doesn't have rounded borders as specified by the stylesheet.

![image](https://user-images.githubusercontent.com/50198413/136892054-bb7496af-516f-4d9c-a43d-10bf89ce8bdb.png)

P.S there is an easy fix to this by just adding a `overflow:hidden` property to the parent element.

**Comment by abh80** [comment]
It was done intentionally by the creator, hence closing this issue

**Comment by omkar342** [comment]
Can you please assign this to me?

**Comment by mohittk** [comment]
> Can you please assign this to me?

Issue closed! @omkar342
