### ISSUE TITLE
Mobile View feature request

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#61]
**Problem**
Mobile view needs to be improved. 

**Needed solution**
When user clicks a certain block, after the block page opens, the other blocks should disappear and go into hamburger button, and upon request, they should shown back, upon clicking on hamburger button.
![image](https://user-images.githubusercontent.com/79041510/137074790-38b85af6-5719-4e98-91cc-600fffcfec9b.png)

**Comment by RashiSingh20** [comment]
@mohittk Hey I would like to work on this. Could you please assign it to me?

**Comment by mohittk** [comment]
> @mohittk Hey I would like to work on this. Could you please assign it to me?

Ohh that's great! You got the feature that I had requested?
If not, please discuss.

**Comment by RashiSingh20** [comment]
@mohittk When the user click on any one of these cards, the others disappear, which can be visible on clicking a hamburger button, where should the hamburger button be placed exactly? I'll try my best to get this feature tho.

**Comment by mohittk** [comment]
> @mohittk When the user click on any one of these cards, the others disappear, which can be visible on clicking a hamburger button, where should the hamburger button be placed exactly? I'll try my best to get this feature tho.

Ahh! Yea.. You got it correct,
Hamburger floating at any corner of the page.

**Comment by RashiSingh20** [comment]
@mohittk Alright.

**Comment by RashiSingh20** [comment]
@mohittk Hey I was trying this out, but just thought of an idea. What if on clicking a card we are redirected to the bottom of the page ( from where the particular component is rendering). The requirement is to display the particular content on clicking the card immediately rather than showing other cards right? Let me know if this could work out.

**Comment by mohittk** [comment]
> @mohittk Hey I was trying this out, but just thought of an idea. What if on clicking a card we are redirected to the bottom of the page ( from where the particular component is rendering). The requirement is to display the particular content on clicking the card immediately rather than showing other cards right? Let me know if this could work out.

Umm.. well, I think it will also do. Just give it a try, let's see how it looks.
