### ISSUE TITLE
Needed to switch Maps api from Google to other alternative.

### ISSUE THREAD

**Issue by mohittk** [space-voyager-21/space-voyager#63]
**Describe the bug**
Google map layout is not working or reloading correctly.
**To Reproduce**
1. Go to 'https://space-voyager.vercel.app/iss'
3. Wait for google to open.

**Expected behavior**
The page should open without any error. For this, I need someone to change the whole map layout to some other map hosting API, like mapbox, or any other, that doesn'nt require billing.

**Screenshots**
![image](https://user-images.githubusercontent.com/79041510/137255607-72dcf916-f3ac-4e50-8c7b-cd1ac002e80f.png)

**Comment by abh80** [comment]
Can I work on this?

**Comment by mohittk** [comment]
> Can I work on this?

Yes! That will be great.
